-- 코드를 작성해주세요
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN
(SELECT FISH_TYPE
FROM FISH_NAME_INFO
WHERE 
    CASE 
    WHEN FISH_NAME = 'BASS' THEN 0
    WHEN FISH_NAME = 'SNAPPER' THEN 1
    ELSE -1
END IN (0, 1));
